# Generated by Django 5.0.7 on 2024-10-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoverCraft', '0004_alter_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='cover',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
