# Generated by Django 5.0.7 on 2024-10-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoverCraft', '0005_user_alter_cover_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Cus',
        ),
    ]
