# Generated by Django 5.0.7 on 2024-10-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoverCraft', '0007_orders_delete_cus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.TextField(default='canada', max_length=500),
        ),
        migrations.AddField(
            model_name='orders',
            name='paymenttype',
            field=models.TextField(default='Cash on delivery'),
        ),
        migrations.AddField(
            model_name='orders',
            name='postalcode',
            field=models.TextField(default='000000', max_length=7),
        ),
    ]
