# Generated by Django 5.0.7 on 2024-10-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoverCraft', '0008_orders_address_orders_paymenttype_orders_postalcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user',
            new_name='username',
        ),
    ]
